import {test,expect} from '@playwright/test';
const defaults={HideForms:false,FormsConvertationCounter:0,FormsConvertationWorkflow:0,FormsConvertationTimeout:0};
test('HideForms governs every figure across reloads and resets without hiding content',async({page})=>{
 await page.addInitScript(()=>localStorage.setItem('paynalton.visual.v1',JSON.stringify({mode:'soft'})));
 await page.goto('/es/sobre-mi/');
 const visibleFigures=page.locator('[data-workshop], .shell-footer-mark, .tn-brand .tn-ornament');
 for(const figure of await visibleFigures.all())await expect(figure).toBeVisible();
 await page.evaluate(()=>(window as any).formsController.setState({HideForms:true}));
 for(const figure of await visibleFigures.all())await expect(figure).toBeHidden();
 await expect(page.locator('[data-reading-ornament]')).toBeHidden();
 await expect(page.locator('[data-workshop] canvas')).toHaveCount(0);
 await expect(page.locator('[data-vortex-trigger]')).toHaveCount(0);
 await expect(page.locator('h1')).toBeVisible();
 await page.reload();for(const figure of await visibleFigures.all())await expect(figure).toBeHidden();
 await page.evaluate(()=>(window as any).formsController.setState({HideForms:false}));
 for(const figure of await visibleFigures.all())await expect(figure).toBeVisible();
 await page.evaluate(()=>(window as any).formsController.setState({FormsConvertationCounter:19}));
 await page.locator('[data-workshop] [data-vortex-trigger]').click();
 await expect(page.locator('html')).toHaveAttribute('data-figures-gone','true');
 await page.evaluate(()=>(window as any).resetForms());
 for(const figure of await visibleFigures.all())await expect(figure).toBeVisible();
 await page.locator('[data-workshop] [data-vortex-trigger]').click();
 expect(await page.evaluate(()=>(window as any).formsController.getState().FormsConvertationCounter)).toBe(1);
});
test('public forms state survives navigation and reset synchronizes tabs',async({page,context})=>{
 await page.goto('/es/');
 const read=()=>page.evaluate(()=> (window as any).formsController.getState());
 await expect.poll(read).toEqual(defaults);
 await page.evaluate(()=> (window as any).formsController.setState({HideForms:true,FormsConvertationCounter:8,FormsConvertationWorkflow:2}));
 await page.reload();await expect.poll(read).toEqual({...defaults,HideForms:true,FormsConvertationCounter:8,FormsConvertationWorkflow:2});
 const other=await context.newPage();await other.goto('/es/sobre-mi/');
 await expect.poll(()=>other.evaluate(()=>(window as any).formsController.getState())).toEqual(await read());
 await page.evaluate(()=>localStorage.setItem('unrelated-state','keep'));
 const reset=await page.evaluate(()=>(window as any).resetForms());expect(reset).toEqual(defaults);
 await expect.poll(()=>other.evaluate(()=>(window as any).formsController.getState())).toEqual(defaults);
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('paynalton.forms.v1')!))).toEqual(defaults);
 expect(await page.evaluate(()=>localStorage.getItem('unrelated-state'))).toBe('keep');
 await page.reload();await expect.poll(read).toEqual(defaults);await other.close();
});
